apiVersion: v1
kind: ReplicationController
metadata:
  name: mavenwebapprc
spec:
  replicas: 2
  selector:
    appname: mavenwebapp
  template:
    metadata:
      name: mavenwebapppod
      labels:
        appname: mavenwebapp
    spec:
      containers:
      - name: mavenwebappcontainer
        image: kanisara/maven-web-application:25
        ports:
        - containerPort: 8080	
...
---
apiVersion: v1
kind: Service
metadata:
  name: mavennodeportservice
spec:
  selector:
    appname: mavenwebapp              #-- > Label of pod
  type: NodePort
  ports:
  - port: 8080                    #--> Service Port
    targetPort: 8080             #--> Container Port
    nodePort: 30300
 
